name: Wandb preempted sweep

on:
  workflow_dispatch:
    inputs:
      sweep_id:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-sweep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install wandb tqdm
    - name: Launch agents
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        export SWEEP_ID="${{ inputs.sweep_id }}"
        python3 launch-agents.py
    - uses: actions/upload-artifact@v4.3.0
      with:
        name: agent-logs
        path: |
          agents/agent_0/out.log
          agents/agent_1/out.log
          agents/agent_2/out.log
          agents/agent_3/out.log
